### ISSUE TITLE
remove from magazine

### ISSUE THREAD

**Issue by omaressameldin** [MohammedAnsary/Wordspace#102]

**Comment by omaressameldin** [comment]
@bassemmagdy @omarelhariry @MohammedAnsary

**Comment by omaressameldin** [comment]
@mayarali

**Comment by mayarali** [comment]
@omaressameldin Sequence diagram 68 the Message returned should be removed and return message object

**Comment by AndrewMagdy** [comment]
Please Resolve Conflicts

**Comment by AndrewMagdy** [comment]
Ex: UserController

**Comment by omaressameldin** [comment]
@AndrewMagdy

**Comment by omaressameldin** [comment]
@AndrewMagdy  @mayarali  @MohammedAnsary @omarelhariry thank you :)
