### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by mohabashraf** [MohammedAnsary/Wordspace#31]

**Comment by bassemmagdy** [comment]
@mohabashraf this is the schema for how to document a piece of code

# Author: your name
# date of the day you started implementing
# a simple description for your code

**Comment by omarelhariry** [comment]
@mohabashraf The top tables are out of the well. Furthermore, the user should have a default profile image.

**Comment by omaressameldin** [comment]
@mohabashraf  add check if user exists

**Comment by mohabashraf** [comment]
@bassemmagdy  @omarelhariry  @omaressameldin

**Comment by omaressameldin** [comment]
@mohabashraf  rename the uml to the correct user stoty

**Comment by mohabashraf** [comment]
@omaressameldin    @bassemmagdy

**Comment by omaressameldin** [comment]
@mohabashraf send user id to the model 
use find article method before the alt box
return user info in case of user is found

**Comment by omarelhariry** [comment]
@mohabashraf writer's name in article should link to his profile

**Comment by mohabashraf** [comment]
@omaressameldin  @omarelhariry

**Comment by mohabashraf** [comment]
@bassemmagdy

**Comment by mohabashraf** [comment]
@omarelhariry  @omaressameldin  please review

**Comment by omaressameldin** [comment]
@mohabashraf 
display profile should be called inside the alt box if the user is found adn not from the view to the view

**Comment by mohabashraf** [comment]
@omaressameldin

**Comment by mohabashraf** [comment]
@bassemmagdy

**Comment by mohabashraf** [comment]
@bassemmagdy  please review

**Comment by bassemmagdy** [comment]
@mohabashraf  user_controller it's enough to write your name one time remove the second one and add its description to the first one

**Comment by mohabashraf** [comment]
@bassemmagdy
