### ISSUE TITLE
User manages his magazine S24

### ISSUE THREAD

**Issue by mayarali** [MohammedAnsary/Wordspace#32]
@omarelhariry  @omaressameldin @MohammedAnsary @bassemmagdy

**Comment by MohammedAnsary** [comment]
Regarding the code, I recommend that you erase the contents of the coverage folder and add the line 
coverage/
to the gitignore file to avoid future conflicts
There are also 4 empty lines in the ability.rb file which should be minimized to 1 line only.
Nothing crucial for reopen.

**Comment by omaressameldin** [comment]
@mayarali  
the ability controller is not needed however it is not wrong :)

**Comment by mayarali** [comment]
@bassemmagdy please review documentation
