### ISSUE TITLE
User adds article to his magazine S28

### ISSUE THREAD

**Issue by mayarali** [MohammedAnsary/Wordspace#33]
@omarelhariry @omaressameldin @MohammedAnsary @bassemmagdy

**Comment by MohammedAnsary** [comment]
Please tag reviewers

**Comment by AndrewMagdy** [comment]
Please Fix Style issues in controllers

**Comment by mayarali** [comment]
@AndrewMagdy  indentation fixed in magazine controller, kindly re-check
