### ISSUE TITLE
User accepts invitation to join a magazine S29

### ISSUE THREAD

**Issue by mayarali** [MohammedAnsary/Wordspace#34]
@omarelhariry @omaressameldin @MohammedAnsary @bassemmagdy

**Comment by mayarali** [comment]
Commit forgot to be linked to this issue
commit 6f545772e64102845b68a4335b15a626f4f1e0c5
commit 3fb7eb8333a33d3a082d28bddac696e10ee47e5c
commit 6f545772e64102845b68a4335b15a626f4f1e0c5 1 parent e57aad4

**Comment by mayarali** [comment]
commit e57aad4c7576362827ae82327e9b79a11d43a112

**Comment by AndrewMagdy** [comment]
Please Fix issues in collaboration and magazine controllers

**Comment by mayarali** [comment]
@AndrewMagdy still working on the issue

**Comment by omaressameldin** [comment]
@mayarali 
request .remove should be inside the alt box as should magazine.add 
expand the alt box to be covering the model as well

**Comment by mayarali** [comment]
@omaressameldin re-check sequence diagram

**Comment by omaressameldin** [comment]
@mayarali 
the last arrow (request.remove) should go from the controller to the model and not from model to view
