### ISSUE TITLE
User searches for an article S06

### ISSUE THREAD

**Issue by MohammedAnsary** [MohammedAnsary/Wordspace#35]
:mag:

**Comment by MohammedAnsary** [comment]
+ 3 new commits on the branch SearchArticle which I forgot to link from the commit messages

**Comment by mayarali** [comment]
@MohammedAnsary return arrows should be dashed not solid arrows

**Comment by MohammedAnsary** [comment]
@mayarali Sequence diagram has been modified

**Comment by omarelhariry** [comment]
@MohammedAnsary Searching for _ gets all articles as an answer

**Comment by MohammedAnsary** [comment]
@omarelhariry  fixed the wildcard problem please recheck

**Comment by MohammedAnsary** [comment]
Self reviewed tests and pass 96% according to simplecov (the rest 4% include avatar uploader and other stuff which are not the scope of this issue)
