### ISSUE TITLE
share on  facebook

### ISSUE THREAD

**Issue by mohabashraf** [MohammedAnsary/Wordspace#36]

**Comment by bassemmagdy** [comment]
@mohabashraf this is the schema for how to document a piece of code

# Author: your name
# date of the day you started implementing
# a simple description for your code

**Comment by AndrewMagdy** [comment]
Please Fix Styling in application controller

**Comment by AndrewMagdy** [comment]
Please FIx styling in Article Show

**Comment by AndrewMagdy** [comment]
Please Fix Styling in Show User view

**Comment by omaressameldin** [comment]
@mohabashraf  add check if article exists

**Comment by AndrewMagdy** [comment]
Please Fix View User

**Comment by mohabashraf** [comment]
Please finish reviewing ASAP so that I can continue working
@bassemmagdy @AndrewMagdy @omaressameldin

**Comment by mohabashraf** [comment]
@bassemmagdy @omaressameldin
