### ISSUE TITLE
add tags to articles 

### ISSUE THREAD

**Issue by mohabashraf** [MohammedAnsary/Wordspace#37]

**Comment by mohabashraf** [comment]
@omarelhariry  @bassemmagdy  @AndrewMagdy  please review

**Comment by omaressameldin** [comment]
@mohabashraf  rename to the correct right story name

**Comment by mohabashraf** [comment]
@omaressameldin

**Comment by mohabashraf** [comment]
@bassemmagdy  @AndrewMagdy  @omarelhariry

**Comment by AndrewMagdy** [comment]
Please Fix Style issues in Controllers

**Comment by omaressameldin** [comment]
@mohabashraf  rename to user story name

**Comment by mohabashraf** [comment]
@omaressameldin

**Comment by mohabashraf** [comment]
@omaressameldin  @AndrewMagdy

**Comment by mohabashraf** [comment]
@AndrewMagdy
