### ISSUE TITLE
User creates a magazine S23

### ISSUE THREAD

**Issue by MohammedAnsary** [MohammedAnsary/Wordspace#45]

**Comment by MohammedAnsary** [comment]
@AndrewMagdy @bassemmagdy @mohabashraf @omaressameldin @mayarali

**Comment by mayarali** [comment]
@MohammedAnsary the last arrow should be aligned with the arrow from if, however it is not a big deal.

**Comment by MohammedAnsary** [comment]
@AndrewMagdy what should I change?

**Comment by AndrewMagdy** [comment]
Same As other story Fix styling errors in controllers Run rubocop on project folder to see all violations

**Comment by MohammedAnsary** [comment]
@AndrewMagdy Please check the style fixations

**Comment by MohammedAnsary** [comment]
Self reviewed tests which cover the magazine model and the part of the magazines_controller that are concerned with this issue
