### ISSUE TITLE
Guest/User views a magazine S09

### ISSUE THREAD

**Issue by MohammedAnsary** [MohammedAnsary/Wordspace#46]

**Comment by MohammedAnsary** [comment]
@omarelhariry @omaressameldin  @AndrewMagdy @bassemmagdy

**Comment by AndrewMagdy** [comment]
Please Fix styling errors in controllers

**Comment by MohammedAnsary** [comment]
No pending tests here

**Comment by MohammedAnsary** [comment]
@AndrewMagdy please recheck

**Comment by omaressameldin** [comment]
@MohammedAnsary the method magazine.show should be called inside the alt box and the return type should be mentioned(like what you did in the else box)
a method findmagazine should be called before the alt box
the word else should be moved to the left a bit to be visible

**Comment by MohammedAnsary** [comment]
@omaressameldin Please re-check
