### ISSUE TITLE
User can like/dislike an article S18

### ISSUE THREAD

**Issue by bassemmagdy** [MohammedAnsary/Wordspace#52]
@mayarali @MohammedAnsary @omarelhariry

**Comment by AndrewMagdy** [comment]
Please Use rubocop

**Comment by bassemmagdy** [comment]
@AndrewMagdy  done

**Comment by omaressameldin** [comment]
@bassemmagdy 
remove the last method upvote/downvote

**Comment by MohammedAnsary** [comment]
@bassemmagdy you can add the pending documentation label and @mina should review your documentation

**Comment by bassemmagdy** [comment]
@MinaHany94 @omaressameldin

**Comment by bassemmagdy** [comment]
@MohammedAnsary

**Comment by MohammedAnsary** [comment]
@bassem I have many errors due to missing controllers and models in your folder please pull master and resolve conflicts then tag me again to review

**Comment by bassemmagdy** [comment]
@MohammedAnsary

**Comment by MohammedAnsary** [comment]
Wrong resolving for conflicts and css errors in almost everyrhing ... please recheck the code

**Comment by bassemmagdy** [comment]
@MohammedAnsary  check branch MergeLikeDislikeArticles and merge I just pulled from master and added the story

**Comment by bassemmagdy** [comment]
@MohammedAnsary

**Comment by bassemmagdy** [comment]
@MohammedAnsary
