### ISSUE TITLE
Promote Article

### ISSUE THREAD

**Issue by mohabashraf** [MohammedAnsary/Wordspace#58]

**Comment by omaressameldin** [comment]
@mohabashraf check if article exists

**Comment by AndrewMagdy** [comment]
Please Fix Show Article indentation

**Comment by omaressameldin** [comment]
@mohabashraf  rename the uml to the correct user story number
send the article id before checking if the article is valid
user method find article to find the article

**Comment by omarelhariry** [comment]
@moh Articles should not be promoted more than once.

**Comment by mohabashraf** [comment]
@omarelhariry  @bassemmagdy  @AndrewMagdy  @omaressameldin

**Comment by AndrewMagdy** [comment]
Please Fix issues in article controller

**Comment by omaressameldin** [comment]
@mohabashraf remove the last three methods in the uml and replace it with one method inside the last alt box in the else part

**Comment by mohabashraf** [comment]
@AndrewMagdy
