### ISSUE TITLE
User can follow/unfollow magazine

### ISSUE THREAD

**Issue by bassemmagdy** [MohammedAnsary/Wordspace#64]

**Comment by bassemmagdy** [comment]
@omarelhariry @mayarali @AndrewMagdy

**Comment by AndrewMagdy** [comment]
Please Use Rubocop

**Comment by bassemmagdy** [comment]
@AndrewMagdy

**Comment by omaressameldin** [comment]
@bassemmagdy 
magazine.isfollowed takes magazine as an argument and not an article
remove the user.unfollow its not necessary

**Comment by bassemmagdy** [comment]
@omaressameldin check the fixed things

**Comment by bassemmagdy** [comment]
@MohammedAnsary

**Comment by MohammedAnsary** [comment]
@bassemmagdy Tests reviewed but code reopened due to style violations in the test file indicated by rubocop + typo in documentation: Authou instead of Author. Please fix and resolve conflicts with master.

**Comment by bassemmagdy** [comment]
@MohammedAnsary

**Comment by bassemmagdy** [comment]
@MohammedAnsary
