### ISSUE TITLE
owner can invite users to be collaborators in magazine

### ISSUE THREAD

**Issue by bassemmagdy** [MohammedAnsary/Wordspace#65]

**Comment by bassemmagdy** [comment]
@MohammedAnsary  @mohabashraf

**Comment by bassemmagdy** [comment]
@MohammedAnsary  done

**Comment by bassemmagdy** [comment]
@omaressameldin

**Comment by omaressameldin** [comment]
@bassemmagdy 
all if statements inside alt boxes should be surrounded by [ ]
try to find article and add altbox for  if maagzine exists 
separate between body of altbox and condition with an empty space

**Comment by bassemmagdy** [comment]
@omaressameldin recheck
