### ISSUE TITLE
Create Home Page List ,Add Article to list and delete Article from List

### ISSUE THREAD

**Issue by mohabashraf** [MohammedAnsary/Wordspace#93]

**Comment by mohabashraf** [comment]
@MohammedAnsary @bassemmagdy  @MinaHany94 @omarelhariry  @AndrewMagdy

**Comment by MohammedAnsary** [comment]
Code reviewing will be the last step after resolving conflicts and being ready to merge. @mohabashraf

**Comment by mohabashraf** [comment]
@omaressameldin

**Comment by mohabashraf** [comment]
@bassemmagdy

**Comment by mohabashraf** [comment]
@MohammedAnsary  @bassemmagdy  @omaressameldin  @mayarali  @AndrewMagdy

**Comment by omaressameldin** [comment]
@mohabashraf 
add parameters to find methods
dont return type f
remove last alt box
change body of alt box before last

**Comment by mohabashraf** [comment]
@omarelhariry  @MohammedAnsary

**Comment by omaressameldin** [comment]
@mohabashraf 
remove square boxes aroudn results and wrtite result insrtead of string
add return statements in the last alt box (else part)
put the statement inside secodn alt box in teh if part not else part
in first alt box return message in else part not if part

**Comment by mohabashraf** [comment]
@MohammedAnsary  @omarelhariry

**Comment by mohabashraf** [comment]
@MohammedAnsary

**Comment by mohabashraf** [comment]
@omarelhariry  typing error

**Comment by mohabashraf** [comment]
@MohammedAnsary

**Comment by MohammedAnsary** [comment]
Tests look fine. Concerning the code, I have few notes. First, please delete the folder vendor/bundle.
Second, I noticed that a Curator cannot add others' articles to the list so please add the permission to ability.rb to be like 
```ruby
return if user.nil?
          can :update, Article do |article|
            article.user_id == user.id || user.curator
          end
```
Third, there're inconsistent indentations in ability.rb. I know we are all to blame for it, but please run rubocop autocorrect.
That's all.
